"""empty message

Revision ID: 735f912dcb55
Revises: bbc37c980ba7
Create Date: 2017-10-30 21:45:52.518160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735f912dcb55'
down_revision = 'bbc37c980ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tag', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ref', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='results_pkey')
    )
    # ### end Alembic commands ###
